name: Build and Publish Monorepo Package
description: Build and publish a package from a monorepo
inputs:
  package-path:
    description: "Path to the package to build and publish"
    required: true
  package-paths:
    description: "Paths to the packages to build and publish"
  github-token:
    description: "GitHub token to use for publishing"
    required: true
outputs:
  version:
    description: "The version of the package that was published"
  published:
    description: "Whether the package was published"
runs:
  using: node16
  main: dist/index.js
